# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('-level', 'points')},
        ),
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
