# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160222_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('-level', 'points', 'created')},
        ),
        migrations.AddField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 22, 13, 40, 50, 555383, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
