# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160222_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 22, 13, 54, 45, 544565, tzinfo=utc)),
        ),
    ]
