# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('img1', models.ImageField(upload_to='q_img')),
                ('img2', models.ImageField(upload_to='q_img')),
                ('level', models.IntegerField(unique=True)),
                ('clue', models.TextField()),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
