# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160222_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numsolved',
            field=models.IntegerField(default=0),
        ),
    ]
