# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_numsolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='clue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
